# Generated by Django 3.2.25 on 2024-11-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_produto_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=255)),
                ('forma_pagamento', models.TextField(blank=True, help_text='Informa como vai pagar', null=True)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Em andamento'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produtos', models.ManyToManyField(related_name='pedidos', to='delivery.Produto')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
